### PR TITLE
Backend gets too slow with fluidcontent extension in case of many pages

### PR DESCRIPTION
**Pull request by almirbi**
The backend started to be very slow after we implemented a fluidcontent site package extension. After profiling it was determined that getPageTsConfig takes a lot of time to execute and renderPageTypoScriptForPageUid is executed unusually too many times, hence the fix.

### CODE REVIEW

**Comment by cweiske** [comment]
Is there a way to disable this cache? During development of new content elements, I would not want to have this cache.

**Comment by almirbi** [comment]
It is only a cache for TSConfig, and will be cleared on Flush cache. We are using this fix in production for a few months now, no problems so far, pages and content elements are added without any issues.

**Comment by NamelessCoder** [comment]
Thanks @almirbi - did you check if this causes issues with `writeCachedConfigurationIfMissing` (which gets called after cache is flushed)? This method uses getPageTsConfig and will itself write the cache - I'm worried about possible infinite recursion (but would be okay if it only causes writing the cached pageTsConfig twice and does not recurse).

**Comment by almirbi** [comment]
Yes, I checked. As mentioned, this runs on production for a few months now.

**Comment by Idleworks** [comment]
Our backend with over 400 pages is also poorly slow with fluidcontent extension installed. Fix provided by Almir seems to work and backend is damn fast again. Thanks mate!
Would be very glad to see this fix in master branch

**Pull request closed without merging**
