### PR TITLE
[BUGFIX] Missing field 'tx_fed_fcefile' in dataStructurePointers

### PR DESCRIPTION
**Pull request by monosize**
FluidTYPO3/flux/issues/1013
works with patch https://review.typo3.org/#/c/44914/

### CODE REVIEW

**Comment by monosize** [comment]
made an update, there was a missing check if $row['CType'] is $this->contentObjectType

**Comment by NamelessCoder** [comment]
There has to be a way to fix this generated DS without using hooks. Anyone providing a DS would be affected by these very same issues and it can't be the solution that each and every one of those implementations must now use a hook to manipulate the TCA that the DS generates. We have to nip this one at the source of the problem: in the generated DS array. It might be incomplete or incorrect, or the core may have experienced a regression in the DS handling.

**Comment by NamelessCoder** [comment]
See https://review.typo3.org/#/c/44914/ - I think that patch should solve the field's DS not being available. See also https://github.com/FluidTYPO3/flux/pull/1032.

**Comment by julianxhokaxhiu** [comment]
The patch is merged on Typo3 master branch but it's still not working. I guess that maybe this PR is needed.

**Comment by mithri** [comment]
With the core patch and this one the FAL fields are working again!

**Comment by NamelessCoder** [comment]
@monosize Is this patch still required after https://github.com/FluidTYPO3/flux/commit/6508a5fb26af1511ab5d6309d7e6ffffcc222f1d?

**Comment by monosize** [comment]
@NamelessCoder the patch is obsolete after FluidTYPO3/flux@6508a5f

**Pull request closed without merging**
